#! /bin/bash
#
# Diffusion youtube avec ffmpeg

# Configurer youtube avec une résolution 720p. La vidéo n'est pas scalée.

VBR="2500k"                                # Bitrate de la vidéo en sortie
FPS="30"                                   # FPS de la vidéo en sortie
QUAL="fast"                                # Preset de qualité FFMPEG medium fast ultrafast
STREAM_URL="rtmp://live.restream.io/live"  # URL de base RTMP youtube ~/Videos/screen/output.flv

KEY=""       # Clé à récupérer sur l'event youtube

ffmpeg \
    -f x11grab -video_size 1366x768 -i :0.0 -f pulse -i default \
    -vcodec libx264 -pix_fmt yuv420p -preset $QUAL -r $FPS -g $(($FPS * 2)) -b:v $VBR \
    -acodec aac -ar 44100 -threads 6 -qscale 3 -b:a 712000 -bufsize 512k \
    -f flv "$STREAM_URL/$KEY"