// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.user_id", "9d6b35ee-5b85-445f-8de5-81e78d0b83d4");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1547294385);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1547294626);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1547294506);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 51200);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{39f83b28-9e51-4a72-a956-ac23df68afdd}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1547294443872");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1547296246872");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1547294401538");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1547298001538");
user_pref("browser.search.region", "BY");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190110060648");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1547294780");
user_pref("browser.slowStartup.averageTime", 17944);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage", "https://ctlos.github.io/wiki/");
user_pref("browser.startup.homepage_override.buildID", "20190110060648");
user_pref("browser.startup.homepage_override.mstone", "64.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "64.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "30a9482e41dd4f3fb667c376c5e59904");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190110060648");
user_pref("extensions.lastAppVersion", "64.0.2");
user_pref("extensions.lastPlatformVersion", "64.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"8139f429-2062-4329-a815-d0a5eb1f0dfa\",\"screenshots@mozilla.org\":\"a530102b-0aa8-4d1b-beb1-dc916e24ddeb\",\"webcompat-reporter@mozilla.org\":\"ac35d744-903a-4ad6-906a-3a89028feab8\",\"webcompat@mozilla.org\":\"4fc589c3-2414-4a20-ae20-bde94aa602aa\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1547294479);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190110060648");
user_pref("media.gmp-manager.lastCheck", 1547294460);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 4969);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("security.sandbox.content.tempDirSuffix", "5116ab00-759e-4ec5-a841-e29b799c7095");
user_pref("security.sandbox.plugin.tempDirSuffix", "ff9db1ec-0879-4817-9204-5d49ac0f7e73");
user_pref("services.blocklist.addons.checked", 1547294669);
user_pref("services.blocklist.gfx.checked", 1547294669);
user_pref("services.blocklist.onecrl.checked", 1547294669);
user_pref("services.blocklist.pinning.checked", 1547294669);
user_pref("services.blocklist.plugins.checked", 1547294669);
user_pref("services.settings.clock_skew_seconds", -209);
user_pref("services.settings.last_update_seconds", 1547294669);
user_pref("services.settings.main.language-dictionaries.last_check", 1547294669);
user_pref("services.settings.main.onboarding.last_check", 1547294669);
user_pref("services.settings.main.sites-classification.last_check", 1547294669);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1547294761);
user_pref("toolkit.telemetry.cachedClientID", "13c38b22-9689-40df-873b-d2f28fcf9773");
user_pref("toolkit.telemetry.previousBuildID", "20190110060648");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
